language: node_js
node_js:
  - lts/erbium

services:
  - docker

before_install:
  - docker pull emscripten/emsdk:1.40.0

script:
  - yarn build
  - yarn test

# before_deploy:
#   - if [ "$TRAVIS_BRANCH" == "master" ];then
#     git checkout master;
#     fi;

before_deploy:
  - git checkout master;

deploy:
  - provider: script
    edge: true
    script: npx auto shipit --dry-run
    on:
      condition: $TRAVIS_PULL_REQUEST == "true" || $TRAVIS_BRANCH != "master"
  - provider: script
    edge: true
    script: npx auto shipit
    on:
      branch: master
